services:
  - type: web
    name: cyberwatch-backend
    runtime: python3
    buildCommand: apt-get install -y nmap && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0